services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=dev
      - PORT=3001
  preprod:
    build:
      context: .
      dockerfile: Dockerfile.preprod
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=preprod
      - PORT=3002
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=prod
      - PORT=3000
